name: TutoPy Tutorial Generator

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Python topic for the tutorial'
        required: true
        type: string

jobs:
  generate_tutorial:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat requests

    - name: Generate Tutorial
      env:
        INPUT_TOPIC: ${{ github.event.inputs.topic }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: python tutopy.py

    - name: Upload Tutorial
      uses: actions/upload-artifact@v4
      with:
        name: python-tutorial
        path: tutorial.py

    - name: Convert to Jupyter Notebook
      run: |
        python jinc.py tutorial.py
        
    - name: Upload Jupyter Notebook
      uses: actions/upload-artifact@v4
      with:
        name: jupyter-notebook
        path: tutorial.ipynb
