name: TutoPy Tutorial Generator

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Python topic for the tutorial'
        required: true
        type: string

jobs:
  generate_tutorial:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat requests

    - name: Generate Tutorial
      env:
        INPUT_TOPIC: ${{ github.event.inputs.topic }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: |
        python tutopy.py
        echo "Contents of current directory:"
        ls -l

    - name: Convert to Jupyter Notebook
      run: |
        TUTORIAL_FILE=$(ls *_tutorial.py)
        if [ -f "$TUTORIAL_FILE" ]; then
          python jinc.py "$TUTORIAL_FILE"
          mv tutorial.ipynb ${INPUT_TOPIC}_tutorial.ipynb
        else
          echo "Error: Tutorial file not found"
          exit 1
        fi

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *_tutorial.py *_tutorial.ipynb
        git commit -m "Add generated tutorial and notebook for ${INPUT_TOPIC}" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
